spring:
  jpa:
    show-sql: false

logging:
  level:
    com.project.handongjudge: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.hibernate.type.descriptor.sql.BasicExtractor: OFF
  logback:
    rollingpolicy:
      max-file-size: 200MB
      max-history: 7
      total-size-cap: 1GB
  file:
    name: /var/log/handongjudge/application.log
